#!/usr/bin/env node
/**
 * NemoMemo release: bump + changelog gate + tag. Two-step on purpose:
 *
 *   pnpm release [patch|minor|major]   # 1st run: scaffolds docs/changelog/vX.Y.Z.md
 *   ...fill in the changelog...
 *   pnpm release [patch|minor|major]   # 2nd run: bumps, commits `release: vX.Y.Z`, tags
 *   git push --follow-tags origin main # (or pass --push to do it for you)
 *
 * The tag push triggers the ghcr versioned-image workflow. The canonical version lives
 * in root package.json and is mirrored into shared/src/version.ts for the app to read.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
const fail = (message) => {
  console.error(`\n🐡 ${message}`);
  process.exit(1);
};

const args = process.argv.slice(2);
const push = args.includes('--push');
const bump = args.find((a) => ['patch', 'minor', 'major'].includes(a)) ?? 'patch';

const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const current = pkg.version;
const [major, minor, patch] = current.split('.').map(Number);
const next =
  bump === 'major' ? `${major + 1}.0.0` : bump === 'minor' ? `${major}.${minor + 1}.0` : `${major}.${minor}.${patch + 1}`;

const changelogDir = path.join(root, 'docs', 'changelog');
const entryPath = path.join(changelogDir, `v${next}.md`);
const entryRel = path.relative(root, entryPath);
const today = new Date().toISOString().slice(0, 10);

// ---- Step 1: no changelog yet → scaffold it and stop -------------------------
if (!fs.existsSync(entryPath)) {
  const template = fs
    .readFileSync(path.join(changelogDir, '_template.md'), 'utf8')
    .replace('X.Y.Z', next)
    .replace('YYYY-MM-DD', today);
  fs.writeFileSync(entryPath, template);
  console.log(`🐠 Scaffolded ${entryRel} for v${next} (${bump} bump from v${current}).`);
  console.log('   Fill in both sections — "What\'s new" in plain language — then run pnpm release again.');
  process.exit(0);
}

// ---- Step 2: validate the entry ---------------------------------------------
const entry = fs.readFileSync(entryPath, 'utf8');
if (!new RegExp(`^---\\s*\\nversion: ${next.replaceAll('.', '\\.')}\\s*\\ndate: \\d{4}-\\d{2}-\\d{2}\\s*\\n---`).test(entry)) {
  fail(`${entryRel} frontmatter must be exactly:\n---\nversion: ${next}\ndate: YYYY-MM-DD\n---`);
}
const section = (name) => {
  const match = entry.split(new RegExp(`^## ${name}\\s*$`, 'm'))[1];
  return match ? match.split(/^## /m)[0] : '';
};
for (const name of ["What's new", 'Technical notes']) {
  const bullets = section(name)
    .split('\n')
    .filter((line) => line.startsWith('- ') && !line.includes('Bold lead phrase') && !line.includes('Precise developer detail'));
  if (bullets.length === 0) fail(`${entryRel} needs at least one real bullet under "## ${name}".`);
}

// ---- Tree must be clean apart from the changelog entry -----------------------
const dirty = git('status', '--porcelain')
  .split('\n')
  .filter(Boolean)
  .filter((line) => !line.slice(3).startsWith('docs/changelog/'));
if (dirty.length > 0) {
  fail(`Working tree isn't clean — commit or stash first:\n${dirty.join('\n')}`);
}
if (git('tag', '-l', `v${next}`)) fail(`Tag v${next} already exists.`);

// ---- Bump + commit + tag -----------------------------------------------------
pkg.version = next;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
fs.writeFileSync(
  path.join(root, 'shared', 'src', 'version.ts'),
  `// GENERATED by scripts/release.mjs — do not edit by hand. \`pnpm release\` bumps it.\nexport const NEMOMEMO_VERSION = '${next}';\n`,
);
git('add', 'package.json', 'shared/src/version.ts', entryRel);
git('commit', '-m', `release: v${next}\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>`);
git('tag', '-a', `v${next}`, '-m', `NemoMemo v${next}`);
console.log(`🌊 v${next} committed and tagged.`);

if (push) {
  execFileSync('git', ['push', '--follow-tags', 'origin', 'main'], { cwd: root, stdio: 'inherit' });
  console.log('🐠 Pushed — the reef updates in ~4 minutes. Just keep swimming.');
} else {
  console.log('   Ship it with: git push --follow-tags origin main');
}
